### ISSUE TITLE
Request - TF1.15

### ISSUE THREAD

**Issue by besherh** [PINTO0309/Tensorflow-bin#16] opened 2019-09-12 10:22 UTC
**[Required]** Your device (RaspberryPi3, LaptopPC, or other device name):  
  
**[Required]** Your device's CPU architecture (armv7l, x86_64, or other architecture name):  
  
**[Required]** Your OS (Raspbian, Ubuntu1604, or other os name):  
  
**[Required]** Details of the work you did before the problem occurred:  
<br>
<br>
<br>
**[Required]** Error message:  
<br>
<br>
<br>
**[Required]** Overview of problems and questions:  
<br> Hello, please note this is not an issue. It rather a new piwheel package for tensorflow 1.15.
Could you provide a pre-built package for the nightly build of TF?
Thanks
<br> This is important, when it comes to deploying deep learning models on edgetpu devices, you need tf2 or tf1.15. The issue with tf2 is this: tflite_runtime package is only tested with tf1.15 and there are a lot of issues with tf2.

<br>

**Comment by besherh** [comment] 2019-09-13 09:23
Thanks for that, could you provide also Tensorflow nightly as wheel package?

Thanks in advance!

**Comment by PINTO0309** [comment] 2019-09-13 09:28
@besherh
Since it is a wheel file built with the contents of the master branch cloned last night, it is the same as nightly.

**Comment by besherh** [comment] 2019-09-16 14:45
actually yes,  I am looking for full version not only the lite one. 
Anyway, thanks!

**Comment by besherh** [comment] 2019-10-02 10:55
Hello,
TF2 is live now. are you planning to make a wheel package for it ?

Thanks

**Comment by PINTO0309** [comment] 2019-10-02 10:56
Already committed. Check the master branch.

**Comment by besherh** [comment] 2019-10-02 14:02
Thanks!

**Comment by filipvg68** [comment] 2019-10-02 14:10
Hi, 
Do you also plan to make the TF 2 wheel package for Debian Stretch? This has been available until beta 1. 

Thanks!

**Comment by PINTO0309** [comment] 2019-10-02 14:17
@filipvg68 
This task is very time consuming, so I excluded binaries that seemed less demanding. Is there a possibility that the stretch environment will last for a long time?

**Comment by filipvg68** [comment] 2019-10-02 14:51
Thank you for the fast response and your support!
I would think that the stretch environment will still be used for some time. It would be very useful to have the binaries for this first official TF2 release for stretch available.

**Comment by PINTO0309** [comment] 2019-10-02 14:57
@filipvg68 
The speed at which rc0-rc2 was released was so fast that I wasn't working. I will challenge later when I have time. I work slowly as a hobby, so don't expect too much. :smiley_cat:

**Comment by filipvg68** [comment] 2019-10-02 15:03
No pressure/worries. Thanks for your help.

**Comment by PINTO0309** [comment] 2019-10-08 15:15
@filipvg68 
Now building. If there are no problems, it can be generated in about 2 days. (TF2.0.0 + Stretch)

**Comment by filipvg68** [comment] 2019-10-08 15:27
@PINTO0309 Many thanks!

**Comment by PINTO0309** [comment] 2019-10-10 10:53
@filipvg68 
I committed.
**tensorflow-2.0.0-cp35-cp35m-linux_armv7l.whl**

**Comment by filipvg68** [comment] 2019-10-10 16:34
@PINTO0309: super, it worked like a charm! Many thanks, much appreciated!

**Comment by PINTO0309** [comment] 2019-10-24 22:36
I have committed the release version of Tensorflow v1.15.0. It has been confirmed that it can be successfully imported with Raspbian Buster.

**Closed by PINTO0309** 2019-10-24 22:36 UTC
Labels: enhancement
